[package]
name = "linkd-adapters"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
linkd-adapters-cargo = { workspace = true }
linkd-adapters-composer = { workspace = true }
linkd-adapters-go = { workspace = true }
linkd-adapters-jvm = { workspace = true }
linkd-adapters-dart = { workspace = true }
linkd-adapters-dotnet = { workspace = true }
linkd-adapters-ruby = { workspace = true }
linkd-adapters-swift = { workspace = true }
linkd-adapters-elixir = { workspace = true }
linkd-adapters-npm = { workspace = true }
linkd-adapters-python = { workspace = true }
linkd-core = { workspace = true }
linkd-pack = { workspace = true }
linkd-sync = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
